### ISSUE TITLE
Crash with Ore excavation

### ISSUE THREAD

**Issue by Sunekaer** [thraaawn/BonsaiTrees#79] opened 2018-11-07 15:06 UTC
**Bonsai Trees version**:1.1.1-b138
**Forge version**:14.23.52768
**I am not using Optifine**: no
**Client Log:** https://pastebin.com/dyn4jZ4S
**Crash Log:** https://pastebin.com/7Av0ecF9

**Steps to reproduce:**
Use ore excavation on multiple Bonsai's

https://github.com/Sunekaer/stoneBlock/issues/556

**Comment by MSandro** [comment] 2018-11-25 13:35
Same issue here!

**Comment by krejcar25** [comment] 2019-01-04 21:23
Same here, uploading more logs, I hope they help...
[crash-2019-01-04_22.10.41-server.txt](https://github.com/thraaawn/BonsaiTrees/files/2728575/crash-2019-01-04_22.10.41-server.txt)
[debug.log](https://github.com/thraaawn/BonsaiTrees/files/2728576/debug.log)
[latest.log](https://github.com/thraaawn/BonsaiTrees/files/2728577/latest.log)

**Comment by thraaawn** [comment] 2019-06-03 17:12
Sorry for the really late reply. Hmm, I can't reproduce this. Is it possible that this has been fixed on OreExcavations end? Or do I need to do anything special to trigger this?

**Comment by krejcar25** [comment] 2019-06-03 18:09
Hi, I cant remember the exact versions of all mods or the modpack now (everything should be in the logs tho...) and in my current playthrough of different modpack I haven't gotten to the point of either bonsais or oreexcavation so I can't be of much help. But if you can't reproduce it, I will gladly trust your skill good sir and wait if it pops up again. 😊 sounds right?

**Comment by thraaawn** [comment] 2019-06-03 20:32
Sounds good. I'll leave the issue open for a while. It might be some other mod interaction.

**Closed** 2022-01-08 17:07 UTC
