### ISSUE TITLE
[1.15.2] Client crash

### ISSUE THREAD

**Issue by JayJay1989** [thraaawn/BonsaiTrees#141] opened 2020-01-26 12:14 UTC
Client crashes with immersive portals.

Cant provide much details about it, but here is the log

log: https://pastebin.com/MKdRkMFc

**Comment by davenonymous** [comment] 2020-01-26 12:43
> Cant provide much details about it, but here is the log

Sorry, that is not enough. I can fix the NPE, but I am not sure what's causing it and why there is null being returned. Since I don't know what you did, not even whether this is happening randomly or when doing something in particular, I won't be able to reproduce this.

Need more information.

**Comment by JayJay1989** [comment] 2020-01-26 14:00
the bonsai hopper was around the nether portal. Removed it resolves the issue. Probably its something with immersive portals.
Also, dirt and tree's are not rendering inside the pot. Breaking them with a pickaxe doesn't give the dirt or tree

http://prntscr.com/qt246g

**Comment by davenonymous** [comment] 2020-01-28 16:11
Well, I've added a null check around that error, fixed the trees in hopping bonsais not rendering and the soil or sapling not dropping.
Will all be included in the next version.

This ticket should be resolved with that. Thanks for reporting!

**Closed as completed by davenonymous** 2020-01-28 16:11 UTC
