### ISSUE TITLE
NPE in CraftTweaker support.

### ISSUE THREAD

**Issue by Darkhax** [thraaawn/BonsaiTrees#91] opened 2019-02-15 00:30 UTC
**Bonsai Trees version**: 1.1.2
**Forge version**: 2806
**I am not using Optifine**: no optifine
**Link to Crashlog**: https://gist.github.com/darkhax/d2955b79ca58ece7c956b2299b8239cd

**Description of the problem including expected versus actual behavior:** When joining a world, I got the crash. I am guessing the world was put into a state that your mod does not account for.

**Steps to reproduce:**
I removed all the default stuff, and then changed the ID of an existing soil type. There are no CraftTweaker scripts in this environment.

**Comment by thraaawn** [comment] 2019-02-15 12:20
I think this is a duplicate of https://github.com/thraaawn/BonsaiTrees/issues/59

**Closed** 2022-01-08 17:07 UTC
