### ISSUE TITLE
[1.14.4] Trees won't go in Bonsai Pots on Servers

### ISSUE THREAD

**Issue by NielsPilgaard** [thraaawn/BonsaiTrees#138] opened 2020-01-12 19:55 UTC
"This tree needs a different kind of soil" message printes no matter the soil and sapling, on servers. It works just fine in SP.

### Screenshots
https://imgur.com/a/fawi0H3

### Versions
- BonsaiTrees-2.0.1.32
- libnonymous-1.14.4-1.0.2.21
- Forge-1.14.4-28.1.109

**Comment by davenonymous** [comment] 2020-01-12 21:14
Hmm, weird. It works in my dev environment. I will look into this more tomorrow.

**Comment by Boomflex** [comment] 2020-01-13 01:14
Just came to report the same thing, very odd!

Looking forward to the fix :)

**Comment by davenonymous** [comment] 2020-01-13 15:07
Hmm, I can't reproduce this in a clean environment using the latest (not yet released) builds. Trying with the older versions now.
Edit: Works fine as well. Hmm, it seems like for example "/reload" causes this to happen. After reloading I can't plant saplings anymore, which is weird, that once worked for sure. But now I have something to look into. Maybe it happens that way in my dev environment too, that would be brilliant. I'll keep you updated.
Edit 2: Jupp. That seems to be causing it. Happens in dev as well. I bet some other mod triggers a reload early on for some weird reason and that's why it seemingly never works on servers. I hope fixing the reload breaking soil compatibility will fix your issues. Back in a few :)

**Comment by Boomflex** [comment] 2020-01-13 15:32
Maybe some weird CraftTweaker interaction as I do have that installed and it does Reload at the world join.

**Comment by davenonymous** [comment] 2020-01-13 15:50
Crafttweaker is not causing it, I have that in my environment since BonsaiTrees supports editing its saplings/soils etc with it (docs for that coming soon).
Anyway currently in the middle of fixing it. The error comes from my assumption that the "RecipesUpdatedEvent" is being called on servers, but it's really only called client side - the docs even say so 😨:  _Fired on {@link Dist#CLIENT} when {@link RecipeManager} has all of its recipes synced from the server to the client (just after a client has connected)_
And with that the rebuilding of the soil to sapling compatibility map only ever got called on the client-side, that's why JEI still showed proper recipes. But the server forgot about it and prevented players from planting their sapling on any soil. Because the mapping was empty.

**Comment by davenonymous** [comment] 2020-01-13 16:01
Didn't mean to immediately close it with that commit, sorry.
Could one of you retest with the latest 2.0.2.35 build from [here](https://github.com/thraaawn/BonsaiTrees/packages/95904)? If that works I'll put it on curseforge.
Edit: Oh, you might also need the latest libnonymous, grab it from [here](https://github.com/thraaawn/libnonymous/packages/95885).

**Comment by Boomflex** [comment] 2020-01-13 16:07
Launching server now, give me 2 mins :)

**Comment by Boomflex** [comment] 2020-01-13 16:19
Confirmed it works :)

https://i.imgur.com/NUuBfKr.png

**Comment by davenonymous** [comment] 2020-01-13 16:25
Awesome. Will release now.
... a few moments later ...
These exact builds should be available on curse once they got approved.

Thanks for the reports and the retest!

**Closed as completed by davenonymous** 2020-01-13 16:25 UTC
