### ISSUE TITLE
[1.18.1] CarryOn BonsaiTrees compatibility error

### ISSUE THREAD

**Issue by gruniu8** [thraaawn/BonsaiTrees#239] opened 2022-01-18 08:30 UTC
when you try to pickup an bonsai pot, and place it back for some reason it places and stays in your inventory, making you unable to play without /clear command (and when playing with a friend, generating infinity bonsai pots, with same upgrades [hoppers and axes] for him/her to use)

**Comment by davenonymous** [comment] 2022-01-18 11:24
Duplicate of #237. This will be fixed in the next release.

**Closed as completed by davenonymous** 2022-01-18 11:24 UTC
